// Saved custom/local OpenAI-compatible endpoints (Wave 45 Phase 2).
//
// Pure reducer operations over the saved-endpoints list + a thin persistence
// wrapper. The API key for an endpoint is NOT stored here — it lives in the OS
// keychain (Rust `local_endpoint_*_key` commands); this store only records
// `hasKey` for UI state.

import { getTweak, setStoredTweak } from "../settings/settings.store";

/** One saved endpoint. `id` is a `crypto.randomUUID()`; `model` is the chosen model name (null until picked). */
export type CustomEndpoint = {
  id: string;
  name: string;
  url: string;
  model: string | null;
  hasKey: boolean;
};

/** The persisted store: the endpoint list + which id is the active/default. */
export type CustomEndpointStore = {
  endpoints: CustomEndpoint[];
  defaultId: string | null;
};

/** Input shape for adding a new endpoint (id is generated by addEndpoint). */
export type NewEndpointInput = {
  name: string;
  url: string;
  model?: string | null;
  hasKey?: boolean;
};

export const EMPTY_STORE: CustomEndpointStore = { endpoints: [], defaultId: null };

/**
 * Append a new endpoint. Generates a `crypto.randomUUID()` id. If the store was
 * empty, the new endpoint becomes the default. Returns the new store and the
 * generated id. Does not mutate the input store.
 */
export function addEndpoint(
  store: CustomEndpointStore,
  input: NewEndpointInput,
): { store: CustomEndpointStore; id: string } {
  const id = crypto.randomUUID();
  const endpoint: CustomEndpoint = {
    id,
    name: input.name,
    url: input.url,
    model: input.model ?? null,
    hasKey: input.hasKey ?? false,
  };
  const endpoints = [...store.endpoints, endpoint];
  const defaultId = store.endpoints.length === 0 ? id : store.defaultId;
  return { store: { endpoints, defaultId }, id };
}

/** Patch an endpoint by id (shallow merge of the provided fields). No-op if id absent. Immutable. */
export function updateEndpoint(
  store: CustomEndpointStore,
  id: string,
  patch: Partial<Omit<CustomEndpoint, "id">>,
): CustomEndpointStore {
  if (!store.endpoints.some((e) => e.id === id)) return store;
  const endpoints = store.endpoints.map((e) =>
    e.id === id ? { ...e, ...patch } : e,
  );
  return { ...store, endpoints };
}

/**
 * Remove an endpoint by id. If the removed endpoint was the default, the default
 * is reassigned to the first remaining endpoint (or null if none remain). Immutable.
 */
export function removeEndpoint(store: CustomEndpointStore, id: string): CustomEndpointStore {
  if (!store.endpoints.some((e) => e.id === id)) return store;
  const endpoints = store.endpoints.filter((e) => e.id !== id);
  const defaultId = store.defaultId === id ? (endpoints[0]?.id ?? null) : store.defaultId;
  return { endpoints, defaultId };
}

/** Set the default/active endpoint by id. No-op if id is not in the store. Immutable. */
export function setDefault(store: CustomEndpointStore, id: string): CustomEndpointStore {
  if (!store.endpoints.some((e) => e.id === id)) return store;
  return { ...store, defaultId: id };
}

/** Return the default endpoint, or null if there is none. */
export function getDefault(store: CustomEndpointStore): CustomEndpoint | null {
  if (!store.defaultId) return null;
  return store.endpoints.find((e) => e.id === store.defaultId) ?? null;
}

/** Load the saved-endpoints store from the settings store (localStorage-backed). */
export function loadEndpoints(): CustomEndpointStore {
  return getTweak("customEndpoints", EMPTY_STORE);
}

/** Persist the saved-endpoints store to the settings store. */
export function saveEndpoints(store: CustomEndpointStore): void {
  setStoredTweak("customEndpoints", store);
}
